export type {TJSON, TJSONObject, TJSONArray, TJSONPrimitive} from "./JSON.spec"
export type {IResult} from "./Result.spec"
export * from "./Result"
export type {ILogger} from "./Logger.spec"
export * from "./Logger"
export type {TMazeJson, IMaze} from "./Maze.spec"
export * from "./Maze"
export type {IWorld, Generation, Solution} from "./World.spec"
export * from "./World"
